package com.mycompany.textimagecamera;

import java.awt.image.BufferedImage;

/**
 *
 * @author ISO53
 */
public class TextImageCameraFrame extends javax.swing.JFrame {

    /**
     * Creates new form TextImageCameraFrame
     */

    RunnableCamera rC;

    BufferedImage image;

    final String USER_DEF_PATH;
    final String CONNECT_CAMERA;
    final String DISCONNECT_CAMERA;

    public TextImageCameraFrame() {
        initComponents();

        USER_DEF_PATH = "C:\\Users\\" + System.getProperty("user.name") + "\\Desktop\\image.jpg";
        CONNECT_CAMERA = "Connect Camera";
        DISCONNECT_CAMERA = "Disconnect Camera";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfrm_trialFrame = new javax.swing.JFrame();
        jpnl_background = new javax.swing.JPanel();
        jbtn_connectCamera = new javax.swing.JButton();
        jpnl_cameraPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtpn_cameraViewTxt = new javax.swing.JTextPane();
        jbtn_takeScreenShot = new javax.swing.JButton();

        javax.swing.GroupLayout jfrm_trialFrameLayout = new javax.swing.GroupLayout(jfrm_trialFrame.getContentPane());
        jfrm_trialFrame.getContentPane().setLayout(jfrm_trialFrameLayout);
        jfrm_trialFrameLayout.setHorizontalGroup(
            jfrm_trialFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jfrm_trialFrameLayout.setVerticalGroup(
            jfrm_trialFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jpnl_background.setBackground(new java.awt.Color(0, 0, 0));

        jbtn_connectCamera.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_connectCamera.setForeground(new java.awt.Color(255, 0, 0));
        jbtn_connectCamera.setText("Connect Camera");
        jbtn_connectCamera.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jbtn_connectCamera.setContentAreaFilled(false);
        jbtn_connectCamera.setMaximumSize(new java.awt.Dimension(89, 22));
        jbtn_connectCamera.setPreferredSize(new java.awt.Dimension(89, 22));
        jbtn_connectCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_connectCameraActionPerformed(evt);
            }
        });

        jpnl_cameraPanel.setBackground(new java.awt.Color(0, 0, 0));
        jpnl_cameraPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        jtxtpn_cameraViewTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jtxtpn_cameraViewTxt.setFont(new java.awt.Font("Segoe UI", 0, 5)); // NOI18N
        jScrollPane1.setViewportView(jtxtpn_cameraViewTxt);

        javax.swing.GroupLayout jpnl_cameraPanelLayout = new javax.swing.GroupLayout(jpnl_cameraPanel);
        jpnl_cameraPanel.setLayout(jpnl_cameraPanelLayout);
        jpnl_cameraPanelLayout.setHorizontalGroup(
            jpnl_cameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_cameraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpnl_cameraPanelLayout.setVerticalGroup(
            jpnl_cameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_cameraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtn_takeScreenShot.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_takeScreenShot.setForeground(new java.awt.Color(255, 0, 0));
        jbtn_takeScreenShot.setText("Take a Screen Shot (.txt of course)");
        jbtn_takeScreenShot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jbtn_takeScreenShot.setContentAreaFilled(false);
        jbtn_takeScreenShot.setMaximumSize(new java.awt.Dimension(89, 22));
        jbtn_takeScreenShot.setPreferredSize(new java.awt.Dimension(89, 22));
        jbtn_takeScreenShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_takeScreenShotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnl_backgroundLayout = new javax.swing.GroupLayout(jpnl_background);
        jpnl_background.setLayout(jpnl_backgroundLayout);
        jpnl_backgroundLayout.setHorizontalGroup(
            jpnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnl_cameraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_connectCamera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_takeScreenShot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnl_backgroundLayout.setVerticalGroup(
            jpnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_connectCamera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_takeScreenShot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnl_cameraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpnl_background);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_connectCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_connectCameraActionPerformed
        // TODO add your handling code here:
        if (jbtn_connectCamera.getText().equals(CONNECT_CAMERA)) {
            jbtn_connectCamera.setText(DISCONNECT_CAMERA);            
            rC = new RunnableCamera(jtxtpn_cameraViewTxt);
        } 
        else {
            jbtn_connectCamera.setText(CONNECT_CAMERA);
            rC.stop();
        }

    }//GEN-LAST:event_jbtn_connectCameraActionPerformed

    private void jbtn_takeScreenShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_takeScreenShotActionPerformed
        // TODO add your handling code here:
        rC.screenShotTxt();
    }//GEN-LAST:event_jbtn_takeScreenShotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextImageCameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextImageCameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextImageCameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextImageCameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TextImageCameraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_connectCamera;
    private javax.swing.JButton jbtn_takeScreenShot;
    private javax.swing.JFrame jfrm_trialFrame;
    private javax.swing.JPanel jpnl_background;
    private javax.swing.JPanel jpnl_cameraPanel;
    private javax.swing.JTextPane jtxtpn_cameraViewTxt;
    // End of variables declaration//GEN-END:variables
}
